import Brightness3Icon from '@mui/icons-material/Brightness3';
import Brightness2Icon from '@mui/icons-material/Brightness2';
import CircleIcon from '@mui/icons-material/Circle';

const Data = [
    {
        event: "Halloween",
        club: "Fashion Parade",
        date: "31st October",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "8:00AM-10:00PM",
        image: '/images/eventPoster/halloween.jpeg',
    },
    {
        event: "Bazzinga",
        club: "English Club",
        date: "3rd November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "8:00AM-10:00PM",
        image: '/images/eventPoster/bazzinga.jpeg',
    },
    {
        event: "Synphonies of Sunsets",
        club: "English Club",
        date: "9th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "8:00AM-10:00PM",
        image: '/images/eventPoster/symphonies.jpeg',
    },
    {
        event: "Campus Star",
        club: "In4mals",
        date: "13th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "8:00AM-10:00PM",
        image: '/images/eventPoster/campusStar.jpeg',
    },
    {
        event: "Tryst With Autumn",
        club: "Team Public Relations",
        date: "15th November ",
        eventStatus: "Finished",
        time: "8:00AM-10:00PM",
        moon: <Brightness3Icon />,
        image: '/images/eventPoster/openMic.jpg',
    },
    {
        event: "Treasure Hunt",
        club: "In4mals",
        date: "18th November",
        eventStatus: "Finished",
        moon: <CircleIcon />,
        time: "10:00AM-12:00PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },
    {
        event: "Battle of Bands",
        club: "Music Club",
        date: "18th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "1:00PM-4:00PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },  
    {
        event: "Opening Ceremony",
        club:"--",
        date: "18th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "4:30PM-5:30PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    
    {
        event: "Devotional Dance",
        club: "Rhythmeecz",
        date: "18th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "4:30PM-5:30PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "Dravida Dance",
        club: "Dravida",
        date: "18th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "4:30PM-5:30PM",
        image: '/images/eventPoster/hillfair-logo-light.png',   
    },   
    {
        event: "Dramatics Performance 1",
        club: "Dramatics",
        date: "18th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "5:40PM-5:55PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "Literacy Mission",
        club:"--",
        date: "18th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "6:00PM-6:00PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "Yogic Self",
        club: "Yogic Self",
        date: "18th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "6:13PM-6:20PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "Band - HP14",
        club:"--",
        date: "18th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "6:45PM-7:45PM",
        image: '/images/eventPoster/hp14.jpeg',
    },   
    {
        event: "Bhangra Performance 1",
        club: "Bhangra Club",
        date: "18th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "7:55PM-8:07PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "Fashion Show",
        club: "Fash P",
        date: "18th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "8:12PM-8:22PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "Artist (DJ Tejas)",
        club:"--",
        date: "18th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "8:30PM-10:00PM",
        image: '/images/eventPoster/djTejas.jpeg',
    },   
    {
        event: "Fashion Show",
        club: "FashP",
        date: "19th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "12:00PM-12:30PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "Music Competition",
        club: "Music Club",
        date: "19th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "1:30PM-2:30PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "Dramatics Play (Auditorium)",
        club: "Dramatics Club",
        date: "19th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "2:30PM-3:30PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "Dravida Classical",
        club: "Dravida Club",
        date: "19th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "5:00AM-5:07PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "NSS",
        club: "NSS",
        date: "19th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "5:08AM-5:15PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "Karate",
        club: "Karate",
        date: "19th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "5:18PM-5:25PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "Dance",
        club: "Rhythmeecz",
        date: "19th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "5:28PM-5:35PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "Yogic Self",
        club: "Yogic Self",
        date: "19th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "5:38PM-5:45PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "Nati Club Performance",
        club: "Nati Club",
        date: "19th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "5:50PM-6:10PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "FashP Performance 1",
        club: "FashP",
        date: "19th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "6:15PM-6:25PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "MIME",
        club: "Dramatics",
        date: "19th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "6:25PM-6:40PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "English Club Skit",
        club: "English Club",
        date: "19th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "6:45PM-7:00PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "Bhangra Performance 2",
        club: "Bhangra Club",
        date: "19th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "7:05PM-7:17PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "Music Club 1",
        club: "Music Club",
        date: "19th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "7:20PM-8:20PM"
    },   
    {
        event: "Dramatics Skit",
        club: "Dramatics Club",
        date: "19th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "8:25PM-8:40PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "Comedian",
        club:"--",
        date: "19th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "8:45M-9:45PM",
        image: '/images/eventPoster/sundeep.jpeg',
    },   
    {
        event: "Dance Competition",
        club: "Rhythmeecz",
        date: "20th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "12:00PM-1:00PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "Dramatics Play",
        club: "Dramatics",
        date: "20th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "2:00PM-3:00PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },    
    {
        event: "Devotional Dance",
        club: "Rhythmeecz",
        date: "20th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "5:00PM-5:08PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },   
    {
        event: "Music Club Performance",
        club: "Music Club",
        date: "20th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "5:15PM-6:10PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },     
    {
        event: "FashP Performance 2",
        club: "FashP",
        date: "20th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "6:15PM-6:30PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },     
    {
        event: "Dravida",
        club: "Dravida",
        date: "20th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "12:00PM-1:00PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },     
    {
        event: "Closing Ceremony",
        club: "--",
        date: "20th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "6:35PM-7:35PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },    
    {
        event: "Nati Club Performance",
        club: "Nati Club",
        date: "20th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "7:50PM-8:00PM",
        image: '/images/eventPoster/hillfair-logo-light.png',
    },    
    {
        event: "TRAP Band",
        club: "STAR NIGHT",
        date: "20th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "8:05PM-9:05PM",
        image: '/images/eventPoster/trap.jpeg',
    },   
    {
        event: "DJ Zephytrone",
        club: "STAR NIGHT",
        date: "20th November",
        eventStatus: "Finished",
        moon: <Brightness3Icon />,
        time: "9:05PM-10:00PM",
        image: '/images/eventPoster/zephyrtone.jpeg',
    },

]
export default Data;